### ISSUE TITLE
作者您好，项目是如何部署到阿里云

### ISSUE THREAD

**Issue by xianengqi** [oliyg/hapiblog#3]
作者您好，我也正在学习hapi，写完了，准备部署到服务器上去，自己有一台阿里云的服务器，安装了nodejs,git 查了一堆资料，说是把项目git clone 到服务器上，然后运行 node app.js 。但是我运行node app.js 报错了。现在有点懵逼中，查了一堆资料，有点无从下手的感觉。刚发了封邮件给您，希望您有空说下服务器部署的思路，在此万分感谢

**Comment by oliyg** [comment]
按理说本地上测试没问题在服务端应该也能跑通；
排查一下是否是文件权限问题或者node 版本问题

**Comment by xianengqi** [comment]
确实是node版本问题，导致es6语法报错，升级到10.13.0后，可以正常跑起来啦，感谢作者：）
